Changes described in Google Drive 'Website Update Sep 2020'
UBC-Snowbots/UBC-Snowbots.github.io pull request #55
Opened 2020-09-22 00:25 UTC by kevinlinxc

Removed team members and subteam dropdown menu until pictures can be taken of new team
Changed front picture and join team picture
Changed copyright to 2020
Updated subteam descriptions, removed subteam descriptions from main page
Added Elsa X to robots
Added IAARC 2018 award
Updated sponsorship package

2020-09-22 00:39 UTC, ihsan314 requested changes
Looks ok so far, just one thing left to do.

2020-09-22 00:39 UTC, ihsan314 commented on challenge.html
> +                <h2 class="align-center">September 30 2020</h2>
Let's not encourage the software challenge, as we're not recruiting for the aspects that it.

Remove it from the site.

2020-09-22 00:50 UTC, ihsan314 approved these changes

2020-09-23 16:54 UTC, raadkhan approved these changes
LGTM

2020-09-23 17:23 UTC, merged